# Generated by Django 5.0.1 on 2024-01-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-pk'],
            },
        ),
    ]
