# Generated by Django 5.0.1 on 2024-01-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=127)),
                ('text', models.CharField(max_length=127)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/expertise/')),
                ('published', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
